build-ceph-deb-native.sh, build-ceph-deb.sh, build-ceph-gcov.sh, build-ceph-notcmalloc.sh, build-ceph-rpm.sh, build-ceph.sh
Because gmock is transitioning to a submodule instead of being inlined.
=> add gmock to the list of directories to remove

build-ceph.sh
Nowadays it's always possible to make check, no need to test for
src/gtest or something.
http://tracker.ceph.com/issues/10766 Fixes: #10766
=> build-ceph.sh always make check

fabfile.py
The previous update was wrong: a number of targets that were supposed to
create packages were actually set to create tarballs instead. The update
allows to run
fab fab gitbuilder_auto
fab fab gitbuilder_ceph_rpm
http://tracker.ceph.com/issues/11052 Fixes: #11052
=> update roles / targets to reflect the current setup

fabfile.py
It does not hurt to install both. On Debian wheezy, /etc/init and
/etc/init.d exist: if installing only in /etc/init, the script won't end
up in /etc/init.d and won't run.
=> try install autobuild-ceph.init and autobuild-ceph.conf

build-ceph.sh
And timeout after 1h instead of 30mn because giant tests take over 20mn
and it's good to have so spare time in case the host is overloaded and
does not respond as fast as it should.
=> build-ceph: run parallel make check when possible

build-ceph-rpm.sh
As Ceph changes and new files get installed by default, we need to ensure that the commits which create these files also update the packaging files lists as well.
One way to do this is to tell Gitbuilder to stop skipping unpackaged files in the RPMs. This will cause Gitbuilder builds to indicate a failure when new files get added without packaging updates.
=> build-ceph-rpm.sh: terminate on unpackaged files

fabfile.py
Instead of a hardcoded SHA. If a new version of master at
https://github.com/ceph/gitbuilder/commits/master is available, it needs
to be used because it presumably contains a fix. If there is a need to
update the fabfile to take advantage of that fix, it's like having pull
request review twice on a commit. Once when it is reviewed prior to
being merged in gitbuilder and once when it is reviewed to be used in
the fabfile.
=> fabfile: always use gitbuilder master

build-ceph-rpm.sh
We don't want that stray --define arg.
Signed-off-by: Sage Weil <sage@redhat.com>
=> build-ceph-rpm.sh: fix rpmbuild for ceph-release file

build-ceph.sh
When a make check fails it is entirely possible that ceph-osd remain,
because they have their own process group. Kill whatever ceph-osd or
ceph-mon are left behind.
We kill ceph-osd / ceph-mon regardless of the success / failure status
of make check because we also want to address the case where a test
pretends to succeed but left daemons behind.
http://tracker.ceph.com/issues/11929 Fixes: #11929
=> tarbal: kill lingering ceph-mon / ceph-osd

build-ceph.sh
be more agressive about killing ceph-mon / ceph-osd as they may be
unresponsive when / if there is a bug.
http://tracker.ceph.com/issues/11929 Fixes: #11929
=> tarbal: kill -9 lingering ceph-mon / ceph-osd

build-ceph.sh
The error code of kill -9 ceph-{mon,osd} must be ignored otherwise the
build may return on error if it fails to kill the process just because
all has been cleaned up as it should.
http://tracker.ceph.com/issues/11929 Fixes: #11929
=> tarbal: kill -9 ceph-mon / ceph-osd always succeed

build-ceph.sh
Because of http://tracker.ceph.com/issues/11931 make check on hammer can
take more than one hour without it being a real problem. So we need to
be more generous with the timeout.
=> make check times out after 1h30 instead of 1h00

build-ceph.sh
Searching the .trs files is not compatible with automake-1.11.
See also https://github.com/ceph/ceph/pull/4923 for more context.
=> the make check output is in test-suite.log

branches-local
If it doesn't exist, behave as before.
Signed-off-by: Sage Weil <sage@redhat.com>
=> branches-local: filter branches by list in 'filter-branches', if it exists

fabfile.py
This skips the dwz compression step.  The debuginfo package is bigger
(from 700M to 1.1G in my test) but it saves about 18 minutes from the
build time.
Signed-off-by: Sage Weil <sage@redhat.com>
=> fabfile: %_find_debuginfo_dwz_opts %{nil}

build-ceph-rpm.sh
Update the .repo files within gitbuilders' ceph-release packages to point at the static location for the GPG public keys.
=> build-ceph-rpm.sh: update URL to GPG pubkeys

build-ceph.sh
Before building we need to get rid of virtualenv created in /tmp as they
may not contain what we expect.
=> cleanup virtualenv found in /tmp

run
When run is executed from /etc/init.d/autobuild-ceph -> loop.sh,
its stdout/stderr are not redirected, so still go to the invoking
user's terminal, which will become unwritable after logout.
Send the logging from run itself to logs/*.
Signed-off-by: Dan Mick <dan.mick@redhat.com>
=> run: Fix logging

build-ceph-rpm.sh
rpmbuild complains at seeing the bogus date:
```
warning: bogus date in %changelog: Tue Mar 10 2013 Gary Lowell - 1-0
warning: bogus date in %changelog: Tue Aug 27 2012 Gary Lowell - 1-0
```
so update the weekday to applease it.
also follows
https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/Packagers_Guide/sect-Packagers_Guide-Creating_a_Basic_Spec_File.html
to remove the hyphen before version number.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> build-ceph-rpm.sh: fix the bogus date in changelog

build-ceph-rpm.sh
Tagged releases get a git-describe with no '-' in the string,
but RPM_VER and RPM_REL still need to get values.  Also,
refactor/simplify a bit.
Signed-off-by: Dan Mick <dan.mick@redhat.com>
=> build-ceph-rpm.sh: set RPM_VER/REL correctly even if on a tag
